### ISSUE TITLE
2017-09-12 Introduction to Arctos as a CMS and community 

### ISSUE THREAD

**Issue by ekrimmel** [ArctosDB/arctos-webinars#1]
**Date & time:** Tuesday, September 12th, 2017 / 3:00 PM EST
 
**Title:** Introduction to Arctos as a community-driven collection management system
 
**Location:** http://idigbio.adobeconnect.com/room
 
**Abstract:** Arctos is both a community and a collection management information system. Join us for an overview of how Arctos provides fundamental collections management and research infrastructure for biodiversity data.
 
As a community, Arctos is a consortium of museums that collaborate to serve data on over 3 million records from natural and cultural history collections. The community provides a collaborative environment for sharing data vocabulary and standards, curating and improving the quality of shared data such as agents and taxonomy, forming strong links between related specimens, and guiding the future development of Arctos.
 
As a collection management information system, Arctos integrates access to data from diverse disciplines (e.g. anthropology, entomology, paleontology, parasitology, etc.) and representing a diversity of content (e.g. specimens, observations, tissues, endo- and ectoparasites, stomach contents, field notes and other documents, and media such as images, audio recordings, and video). This webinar will briefly cover the primary collection management tools Arctos offers for curating these data.
 
**Presenters:** Carla Cicero (Staff Curator of Birds, Museum of Vertebrate Zoology at the University of California, Berkeley) & Mariel Campbell (Collection Manager, Museum of Southwestern Biology at the University of New Mexico)
 
**Moderator:** Erica Krimmel

**Comment by ekrimmel** [comment]
26 attendees.

Post-webinar recording available here: https://www.youtube.com/watch?v=miVsxdMuGEs

**Comment by mkoo** [comment]
Posted on arctosdb.org and youtube
