### ISSUE TITLE
2017-12-12 Projects, Publications, and Citations

### ISSUE THREAD

**Issue by ekrimmel** [ArctosDB/arctos-webinars#10]
Want a webinar covering how to use projects and publications in Arctos.

Michelle or Carla could present.

**Comment by ekrimmel** [comment]
**Potential abstract:** Arctos is both a community and a collection management information system. It provides fundamental research infrastructure for biodiversity data, and is intended for  curators, collection managers, investigators, educators, and anyone interested in natural and cultural history. Over 3 million records are publicly available from 20+ collaborating institutions.

This webinar will provide an overview of how Arctos captures and connects information with Projects, Publications, and Citations. These features help track specimens and collection objects for the entirety of their lives, from acquiring project funding to being used for cutting-edge research 50 years in the future.

**Comment by ekrimmel** [comment]
@mkoo, at the AWG meeting today @campmlc and @jldunnum volunteered to assist with this webinar. In light of how it was difficult timing-wise to have three presenters for the October webinar, I vote John & Mariel duke it out for who wants to present, but have the other person still on board to moderate questions in the chat, and for extra expertise on hand.

All three of you, [here is the calendar announcement with abstract](https://www.idigbio.org/content/arctos-webinar-series-projects-publications-and-citations)--let me know if you'd like anything other than the presenter names updated.

**Comment by ekrimmel** [comment]
scheduled sound check for 2017-12-04 at 3pm Eastern

**Comment by ekrimmel** [comment]
recording: https://www.youtube.com/watch?v=n06u4rni5z8&list=PLA1YSv1rn8XcR6Pe0qyNuM8h07GB87bMh&index=5

**Comment by AJLinn** [comment]
I can't wait to watch it over Christmas break! ;-) (I ended up missing it because of a huge, mistaken, delivery of chemicals to our museum.)

**Comment by mkoo** [comment]
Posted on arctosdb.org and youtube
