### ISSUE TITLE
Media

### ISSUE THREAD

**Issue by ekrimmel** [ArctosDB/arctos-webinars#13]
Want a webinar on media features and cataloging in Arctos.

@ccicero and @mkoo volunteered to present, using MVZ photo vouchers as examples.

**Comment by Jegelewicz** [comment]
From 2018-07-12 AWG Meeting Notes:

> January: Media (Mariel; Angie; Michele; UAM ES or Herb -->pushing images to TACC)
> How to link/incorporate with/talk to DAM systems

**Comment by Jegelewicz** [comment]
Link at iDigBio? Arctos Webinars page?

**Comment by ebraker** [comment]
yep and sent link to @KyndallH to post on Arctosdb

**Comment by Jegelewicz** [comment]
I wanted to send the link to peeps in Australia... You rock!
