### ISSUE TITLE
2018-06-12 Arctos Open Office Webinar

### ISSUE THREAD

**Issue by ekrimmel** [ArctosDB/arctos-webinars#17]
Idea from AWG mtg 2018-01-11 is to have a drop-in webinar similar to office hours. Have the option for participants to submit questions early. 

Tentatively scheduled for June, have people signed up as mentors show up.

**Comment by mkoo** [comment]
Sent for distribution 6/7/2-18:
~~~~~~~
Notice: Next in the Arctos Webinar series:

June 12th, Tuesday at 3 PM ET
Link: https://idigbio.adobeconnect.com/room 

Come talk to other Arctos users directly and get your answers about Arctos. Not an Arctos user but curious about how we operate as a management system and community? Here's the chance to discuss Arctos, too. 

Our next webinar in the Arctos series will be an open office format where we will answer questions, show off some new handbook details and hear what is on your mind about Arctos.

https://www.idigbio.org/content/arctos-open-office-hours

Thanks with appreciation, Arctos Working Group!

**Comment by mkoo** [comment]
Post-webinar survey link: (add to slideshow)
We usually ask participants to complete a brief survey; we need info for our NSF reports (to justify adobeconnect, etc.) and we use the survey in lieu of requiring registration.

Here is a link to the survey
https://tinyurl.com/ArctosiDigBioWebinarOfficeHour

**Comment by mkoo** [comment]
Also Shared Doc for questions is here: https://docs.google.com/document/d/1-sIl7rP-lckWhhdcCxiWRg3nBirKG6BEhg5cqUojcO0/edit
