### ISSUE TITLE
how-to GitHub (internal)

### ISSUE THREAD

**Issue by dustymc** [ArctosDB/arctos-webinars#18]
From Arctos AWG meeting: hold a "how to github" webinar- less-shared than normal iDigBio webinars

- how to file an issue
- how to participate 
    - prioritize Issues
    - how-tos

**Comment by ewommack** [comment]
I would really love some more about how to get around in github.

**Comment by ebraker** [comment]
We can schedule an internal AWG/Arctos user webinar for navigating github this summer...I'm sure it would benefit many of us. We can record it and post it with our other webinar for folks who can't attend.

**Comment by dustymc** [comment]
We should first clarify some internal workings.

Currently I believe not-AWG users (and maybe not all of us??) cannot add metadata (labels, prioritization, projects, etc.) to Issues. The AWG is (was?) supposed to do that, but I don't think that happens very effectively. I tentatively propose that we invite anyone with an Arctos operator account to join Team "Users" (but see below).

Here's a preliminary organizational proposal:

- owners: maybe 1 from each institution - as few as possible, but enough that one is usually around (I think only Owners can assign Users to Teams). See https://github.com/ArctosDB/arctos/issues/1451 and https://github.com/orgs/ArctosDB/people?utf8=%E2%9C%93&query=+role%3Aowner
- Team "Users" - write access to https://github.com/ArctosDB/arctos (=can label/etc. Issues in https://github.com/ArctosDB/arctos/issues). I want to say Operators get invited to this by default, but this Team can also change UI code - I don't think it's possible to allow write access to Issues without also allowing write access to the code. Is everyone comfortable with that? I'm not sure I am, but have no better ideas.
- Team "Documentation" - write access to https://github.com/ArctosDB/documentation-wiki (eg, can create/change how-tos and documentation). Anyone willing to read the how-to-how-to and contribute is welcome to join.
- Team "DBA" - write access to https://github.com/ArctosDB/DDL. Probably only a couple of us, although I certainly have no objections to allowing anyone in.
- Team "Webinar" ("Communication"?) - write access to https://github.com/ArctosDB/arctos-webinars. Not sure who this should be (but I'm posting here now with no intention of excluding anyone willing to help!)
Team "Outreach" - write access to https://github.com/ArctosDB/new-collections. Not sure who this should be.

@mkoo (and anyone else who knows how GH works!) - help please!

**Comment by campmlc** [comment]
I support this. Carla, Teresa, and I need write access to new collections.
I'm also willing to do documentation.
Should AWG officers have access to particular groups?
I don't necessarily want access, but we should decide who has it if needed.

**Comment by sharpphyl** [comment]
Is this thread still alive?  PLEASE do a webinar on how to use GitHub - what it is, how to use it, what issues belong where, how to create or make changes to how tos and/or (or not) documentation, what you can destroy and what you can't, how to avoid 100 emails a day but still stay in touch, etc. etc.  It's our primary communication tool but I think most of us learn how to deal with it by trial and lots of error.

**Comment by ebraker** [comment]
Yes @sharpphyl, this thread still lives. We had talked about making a recording in Zoom or just doing an internal webinar without broadcasting to the list serv masses, so we can prioritize this. Any interest in heading this up @mkoo or @Jegelewicz ?

**Comment by lin-fred** [comment]
This would be useful - I think this is what took me the longest at first to get started. I had never used Github before and I didn't know any of the basics of its use, let alone managing our movement into Arctos with it. I've been getting the hang of it now but I'm still not sure what I can and can't do with it.

I really like it's management, so I'm looking forward to learning how to use its features!

**Comment by campmlc** [comment]
Emily, can we do an internal webinar with Adobe Connect?

**Comment by ebraker** [comment]
That should be fine. Once we figure out a presenter, I can book us a room on Adobe Connect to meet (and record).

**Comment by mkoo** [comment]
The idea is still alive (me, jury's still out).

We can do a Zoom webinar (which has all the bells and whistles of AC) so
that is not an issue.

Scheduling is a challenge and the earliest might be May 7th for me. BUT I
am also happy to help anyone if they just want to call me!

**Comment by campmlc** [comment]
Maybe we can do it in the form of an open help session. Michelle, if we do
a couple of help sessions, could these be recorded, edited, and compiled
into a single webinar? That way we could start something sooner?

**Comment by mkoo** [comment]
Mariel, I like that suggestion!
Less for me to prep too (I think) so let's do that. Who should I talk to
about best dates?

**Comment by campmlc** [comment]
Let's do a doodle poll?

**Comment by Jegelewicz** [comment]
I think I use GitHub for Arctos more than anyone besides Dusty, so I would be happy to help out with this.

**Comment by dustymc** [comment]
I'm happy to help too!

>how to avoid 100 emails a day but still stay in touch

But mostly I just want an answer to that...

**Comment by Jegelewicz** [comment]
>>    how to avoid 100 emails a day but still stay in touch
> 
> But mostly I just want an answer to that...

It's very simple. DON'T get any of the emails! In your profile select settings > Notifications and change "watching" and "Participating" to "Web"

![image](https://user-images.githubusercontent.com/5725767/55844860-a2236d80-5afc-11e9-9d3f-a7fde126b868.png)

THEN set a reminder to go to GitHub and select the little blue bell next to your avatar

![image](https://user-images.githubusercontent.com/5725767/55844913-d565fc80-5afc-11e9-89aa-27894468ca47.png)

You will be rewarded with a list of unread notifications. You can peruse the list, read the issues that interest you and mark those that don't as "read". I do this about twice a day, but depending upon the level you wish to participate, you might check less often.

This is how I manage my GitHub participation without receiving a single email from GitHub.

**Comment by sharpphyl** [comment]
WOW!  This is why we need a webinar on GitHub.  I'm editing my profile immediately.  Thanks so much Teresa!

**Comment by ebraker** [comment]
@mkoo do you want to create a doodle poll based on your availability and share with @Jegelewicz and @dustymc to coordinate a time to head up a GitHub Help Session? Ideally some time in May or June? Hopefully other AWG folks can attend whatever date you settle on, but we'll have the recording archived as a resource.

**Comment by mkoo** [comment]
Good idea: Vote here for your best times--
https://doodle.com/poll/ixvwvn4v47ambmw3

Doodle.com is infested with ads now and I cant see how to send an
administrator link so Teresa and Dusty can edit the dates; so let me know
if I should add or remove options.

Teresa, we should have a call before hand to outline a few must-show github
tips!

**Comment by campmlc** [comment]
OK, I responded, but heads up that the May 30 and May 31 dates are during
the SPNHC meeting. We might be able to participate from there, but may be
kind of crazy.

**Comment by sharpphyl** [comment]
> THEN set a reminder to go to GitHub and select the little blue bell next to your avatar

I think I added the Reminder app but can't figure out where it is now.  Is that what you're referring to, Theresa?  Maybe you can add that to the agenda.

**Comment by mkoo** [comment]
OK, now that Teresa has weighed in, I'd like to close the doodle poll.
Let's schedule for Tuesday June 18, 11 AM (AK)/ 12-1 (PT)/ 3-4 (ET)
On my calendar!

That removes the conference conflicts too!

**Comment by ebraker** [comment]
Awesome, thanks Michelle! What's your preference - Zoom or Adobe Connect? If AC, let me know and I'll book the 6/18 time slot.

**Comment by Jegelewicz** [comment]
THEN set a reminder to go to GitHub and select the little blue bell next to your avatar

I think I added the Reminder app but can't figure out where it is now. Is that what you're referring to, Theresa? Maybe you can add that to the agenda.

@sharpphyl just set a reminder on your personal calendar, not in GitHub. I have a habit of checking the blue bell in the morning when I get in, just after lunch, and again before I leave for the day.

**Comment by sharpphyl** [comment]
Thanks.  Got it.

**Comment by ebraker** [comment]
scheduled for June 18 @ 1pm MT/ 12pm PST on Zoom (https://berkeley.zoom.us/j/363481382)

**Comment by mbprondzinski** [comment]
So, the most confusing part is knowing when I am part of the conversation or just receiving comments from various issues that don't involve me.

**Comment by Jegelewicz** [comment]
@mkoo I appropriated the "why use GitHub" and changed it to "Getting Started", then re-arranged the articles on the Resources page. I think this gives us a place to start!

**Comment by Jegelewicz** [comment]
> So, the most confusing part is knowing when I am part of the conversation or just receiving comments from various issues that don't involve me.

@mbprondzinski see new documentation at https://handbook.arctosdb.org/how_to/How-to-Use-Github-for-Arctos.html#watching-vs-participating let me know if that answers your question!

**Comment by mbprondzinski** [comment]
Okay, thanks!  I will take a closer look at this.

**Comment by mkoo** [comment]
Specific to the point of Teams and access-- I started to clean these up
last week and these are good recommendations that I can implement. Where
possible I may convert a group's permission instead of creating a new group
and will update once I get a handle on all these new permissions levels and
roles.
updates to come
