### ISSUE TITLE
2017-10-10 Basic and Advanced Searching in Arctos

### ISSUE THREAD

**Issue by ekrimmel** [ArctosDB/arctos-webinars#2]
**Date & time:** Tuesday, October 10th, 2017 / 3:00 PM EST

**Location:** http://idigbio.adobeconnect.com/room

**Title:** Basic and Advanced Searching in Arctos

**Abstract:** Arctos is a community of museums that collaborate to manage and host their data online. Over 3 million records are publicly available at https://arctos.database.museum, a searchable biodiversity database for scientific research, resource management, and education. The Arctos database can be queried on multiple levels, including taxonomy, geography, collection or identifier, agent name, part or attribute, and relationship, as well as for media such as images, audio recordings, and video. Search parameters and results can be customized by the user, mapped in BerkeleyMapper or Google Earth, and saved in a user profile or downloaded as csv, tab-delimited text, or xml.

While data are served and shared through the public portal, specimen data are protected at the curatorial level through the virtual private databases of each Arctos collection. Sensitive information may be encumbered from public view at the discretion of the individual collections.

This webinar will provide a short introduction to the variety of basic and advanced search tools available in Arctos using Gold Standard examples to illustrate different types of search parameters and the integration of multiple data sources including projects, relationships, citations, and publications.

**Presenter/s:**  Jonathan Dunnum and Mariel Campbell (Collection Managers, Museum of Southwestern Biology at the University of New Mexico), and Kyndall Hildebrandt (Collection Manager, Museum of the North, University of Alaska, Fairbanks)

**Moderator:** Erica Krimmel (Assistant Collection Manager, Chicago Academy of Sciences)

**Comment by ekrimmel** [comment]
recording: https://www.youtube.com/watch?v=lY5kDQNQ8VA

link added to readme on this repository, as well as Arctosdb.org and iDigBio wiki

**Comment by mkoo** [comment]
Posted on ARctosdb.org and youtube.
