### ISSUE TITLE
2018-10-09 Geography #1 - Big structure; interrelated tables

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos-webinars#20]
From AWG 2018-07-12 meeting notes:

> October 9th webinar Geography & Locality - Michelle will do it - any other volunteers?? Maybe Tom (Teresa will ask); Aren (Angie will ask); Andrew will help. Emily will assist with webinar.
> Big structure; interrelated tables

**Comment by Jegelewicz** [comment]
Tom has agreed to help.

> 

> Tom,
> Michelle is planning to manage the Arctos webinar on October 9 which will cover geography. Would you be willing to help out, either planning the session or manning the chat box during the webinar?
> Thanks!
> Teresa 

> Howdy! Yes to both, please.
> Tom

**Comment by ebraker** [comment]
Abstract:
In the first of two of our Geography webinars, we will focus on how the Arctos database models and organizes geographic information (including localities). We view Geography in Arctos as fundamental data that, together with a timestamp, adds critical value to a specimen or an observation; it is what transforms a preserved organism into a scientific specimen. However, geographic information is often not as easily recorded and standardized as, say, physical measurements. Arctos uses a series of tables to normalize as much as possible all geographic information that is shared among collections in Arctos while still allowing each collection control over georeferencing textual geographic descriptions of localities and allow sharing of common ones. We will demonstrate this data structure and how implementation of consistent geographical standards allows Arctos to offer the most useful locality data possible. If time allows, we will discuss work in progress and future goals for geographical data in Arctos.

In the second part of our Geography webinars on November 13th, we will focus on georeferencing and best practices of locality management: How Arctos handles geographical data (Part 2: georeferencing in Arctos)
