### ISSUE TITLE
Taxonomy #2 - Using the Heirarchical Editor to Improve Arctos Taxonomy

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos-webinars#22]
An intro to the hierarchical editing tool. Possibly in May or June of 2019.

**Comment by Jegelewicz** [comment]
This tool is not really functional so I am going to close this.

**Comment by dustymc** [comment]
I'm not reopening and I don't think a webinar is necessary, but the tool is functional and is being used to manage at least one collection's taxonomy.

**Comment by Jegelewicz** [comment]
If someone is actually using it, then I would love to have them do this - I have not even tried because it was not functional for the ginormous amount of taxa I was working with.

**Comment by dustymc** [comment]
https://arctos.database.museum/info/ctDocumentation.cfm?table=cttaxonomy_source#current_reptile_classification

>not functional for the ginormous amount of taxa

Not surprising - that's a VERY straightforward tool, doesn't much try to avoid eating your browser. That could potentially be changed, but I'd really rather see something like https://globalnames.org/apps/gnite/ happen.
