### ISSUE TITLE
Geology Webinar - February 2020

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos-webinars#23]
Suggested topic. Presenters needed from Paleo collections.

**Comment by ebraker** [comment]
Any interest in presenting a webinar on paleo collections in Arctos sometime this fall @Jegelewicz ? Besides UAM, it looks like UTEP has the most extensive Arctos experience for this collection type.

**Comment by Jegelewicz** [comment]
Actually, ALMNH, NMMNHS, and UNM are the collections with the most use. I have entered the majority of ALMNH, Dustin Perriguey has done all of the UNM stuff, and Nicole is just embarking on the NMMNHS stuff. We could possibly put something together for later in the fall. I will be meeting with both Dustin and Nicole later this month and I'll see what they want to do.

**Comment by ebraker** [comment]
@Jegelewicz that sounds great. Let me know the verdict. We have a clean slate for Fall webinars so you all would have your pick of 2nd Tuesdays for a paleo overview webinar.

**Comment by Jegelewicz** [comment]
After lunch with Nicole and Dustin, we think we need to have a discussion with Dusty plus some of the other paleo people to refine Geology before giving a webinar. I'll set up a Doodle poll to get us together for a chat. Depending on what gets discussed, we may be able to do a webinar in the fall or we may have to wait for some development to get completed.

**Comment by ebraker** [comment]
Sounds like a good plan, thanks for discussing with Nicole and Dustin.

**Comment by ebraker** [comment]
Checking in on the status of Paleo migration and Arctos Geology structures. Do you think a late winter webinar is doable? Ideally February 10 but the schedule is open if it has to wait...

**Comment by Jegelewicz** [comment]
Emily, I think we could take this up on February 10. I need to recruit at least one other person to help out, but that shouldn't be too hard. When do you need the abstract?

**Comment by ebraker** [comment]
Excellent! That would be amazing. I'll need the abstract by Jan 24. Thank you!

**Comment by Jegelewicz** [comment]
/remind me to follow up by December 31, 2019

**Comment by ebraker** [comment]
Following up - @Jegelewicz, are we still OK to move on this topic? Are Nicole and Dustin planning on presenting with you? Let me know and I'll reach out to confirm and ask for an abstract.

**Comment by Jegelewicz** [comment]
UGH! Yes we should Just Do It. @Nicole-Ridgwell-NMMNHS are you in?

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
This is needed, but at the same time I wish we could wait until after the post-postgres geology attribute expansion that we are planning for. I'm in whatever we decide to do.

**Comment by Jegelewicz** [comment]
I think it's OK to have one now. The stuff that is there needs some explanation and we can do another when we make all the changes after PG. That's a long way off yet. I'll throw an abstract up here before the start of next week.

**Comment by Jegelewicz** [comment]
/remind me to write an abstract on Friday

**Comment by Jegelewicz** [comment]
> Geology in Arctos
> 
> Did you know that you can record geologic information in Arctos? Whether you have never used this functionality or you are familiar with it, this webinar will have something for you!
> 
> We will walk through the Geology code table, discuss how geology relates to locality, add geology to a locality, and talk about the future of geology and "locality attributes". Be ready to learn all bout the different geologic possibilities and maybe even see a dinosaur.....

@Nicole-Ridgwell-NMMNHS how does this sound?

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Sounds good! Since we are at a point where we are planning future changes, maybe we should also add in a little time for people to make suggestions on those changes.

**Comment by Jegelewicz** [comment]
@ebraker here is the abstract

Geology in Arctos

Did you know that you can record geologic information in Arctos? Whether you have never used this functionality or you are familiar with it, this webinar will have something for you!

We will walk through the Geology code table, discuss how geology relates to locality, add geology to a locality, and talk about the future of geology and "locality attributes". There will be time for questions so bring those that you have already or add some to the chat as we go along. Be ready to learn all bout the different geologic possibilities and maybe even see a dinosaur.....

**Comment by Jegelewicz** [comment]
@dustymc in preparation for this would it be possible to make [this](https://github.com/ArctosDB/arctos/issues/2296) happen by Monday?

**Comment by dustymc** [comment]
>d talk about the future of geology and "locality attributes". 

Perfect, I was going to suggest that this is a good opportunity to talk briefly about the Arctos development model. In short:

* we added geology when we got our first collection that needed it
* turns out there's more stuff in the same sort of relationship to places, we're generalizing to accommodate (and the original model is flexible enough to mostly serve the purpose until we can find time to make real changes).

I noticed yesterday on http://www.spnhc-icomnathist2020.com/workshops/

>then gather member input for development plans and priorities.

where Arctos is constantly and directly responding to selective pressures from users, which I think is a fundamental difference.

Also worth mentioning the 'private' "geology" attribute - what was modeled for information about rocks and time turns out to be useful in selectively masking various place-and-time data for threatened snakes and etc.

>Monday

Oh boy, I'll give it a shot....

**Comment by ebraker** [comment]
Great! Thanks. Will you also introduce some Paleo-specific features in Arctos (e.g., part name vocab, taxonomy tables, media) and mention other capabilities? (Essentially a mini-tour of Arctos for people who are CMS shopping).  If so, can we add a sentence in the abstract along these lines, "This webinar will provide an overview of Arctos features and functions pertaining to managing Paleontology and Geology collections data. We will also walk through...." ?

**Comment by Jegelewicz** [comment]
@ebraker How about

> Time permitting, we will also delve into other Arctos features that are useful for managing Paleontology and Geology collections.

I'd like to leave it vague so we can decided what might fit best as we plan the webinar structure.

**Comment by ebraker** [comment]
@Jegelewicz that's perfect, thank you!

**Comment by ebraker** [comment]
Details: Tuesday, February 11 @ 1pm MT (3PM ET)

**Comment by ebraker** [comment]
Teresa and Nicole - can we get a soundcheck on the calendar for next week? Nicole - since you haven't presented a webinar before, the soundcheck allows us to test our screen share and sound quality in Adobe Connect in advance of the webinar, as well as provides some time for the presenters to chat about content if desired. Should be quick (~15-20 mins) unless you want to take extra time to go over the webinar. I'm free afternoon Feb. 5th, morning Feb. 6th, and all day Feb 7.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
How about the 7th at 2pm? My schedule is flexible though and I can do another day/time if needed.

Nicole Volden
Geoscience Collections Manager
New Mexico Museum of Natural History and Science
1801 Mountain Road NW
Albuquerque, NM 87104-1375
505-841-2843
nicole.volden@state.nm.us<mailto:nicole.volden@state.nm.us>
www.nmnaturalhistory.org

**Comment by ebraker** [comment]
Feb 7 @ 2pm works for me (and the [Adobe Connect room](https://idigbio.adobeconnect.com/room?launcher=false) is free at that time). Let us know if that works for you @Jegelewicz and I'll book it.

**Comment by Jegelewicz** [comment]
Works for me - only now I have to actually plan the webinar!

**Comment by ebraker** [comment]
Ok great! It'll be awesome - happy planning ;)

**Comment by ebraker** [comment]
Not sure if you saw my email last week - are either of you on any Paleo list servs? If so, would you mind circulating the webinar announcement so that we can target folks with a specific interest in using geology CMS tools? Announcement text below.

Please join us for a webinar on Geology in Arctos.
 
Abstract: Did you know that you can record geologic information in Arctos? Whether you have never used this functionality or you are familiar with it, this webinar will have something for you! We will walk through the Geology code table, discuss how geology relates to locality, add geology to a locality, and talk about the future of geology and "locality attributes". There will be time for questions, so bring those that you have already or add some to the chat as we go along. Be ready to learn all about the different geologic possibilities and maybe even see a dinosaur... Time permitting, we will also delve into other Arctos features that are useful for managing Paleontology and Geology collections.
 
Presenters: Teresa Mayfield-Meyer and Nicole Ridgwell, New Mexico Museum of Natural History & Science.
 
When: Tuesday, February 11, 2020 at 3:00pm ET
 
Where: https://idigbio.adobeconnect.com/room
 
Can’t Make It?: View archived recordings here https://arctosdb.org/learn/webinars/

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
Sorry - saw it and had so many other things going on that it got buried. I've forwarded this to preplist.

**Comment by ebraker** [comment]
Perfect, thanks!
