### ISSUE TITLE
We need to update iDigBio Arctos webinar page

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/arctos-webinars#24]
Last update was Feb 2018!

https://www.idigbio.org/wiki/index.php/IDigBio_Working_Groups#Arctos_Working_Group

**Comment by ccicero** [comment]
Who has access to do that?

**Comment by ebraker** [comment]
I didn’t realize that they maintained webinar recording links. I can check with Molly Phillips to see who maintains the idigbio page and get our newest links posted.

On Jan 22, 2019, at 10:44 PM, Carla Cicero <notifications@github.com<mailto:notifications@github.com>> wrote:


Who has access to do that?

**Comment by ebraker** [comment]
Done!
