### ISSUE TITLE
Low Quality Dashboard

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos-webinars#29]
@Jegelewicz what do you think about doing an intro to the dashboard and mini-recap of our SPNHC talk for a webinar?

**Comment by Jegelewicz** [comment]
Oh yeah - that would be really good. Just say when.

**Comment by ebraker** [comment]
Awesome! I'm thinking the 2nd Tuesday in September or November (Aren is on the docket for October). Probably up to you since I'd like to schedule the GitHub Documentation how-to in one of those slots and I'm hoping to rope you and Michelle into that (again...sorry :/). I'm free either month for the Dashboard/Metrics webinar. Let me know if you have a preference and then I'll reach out to Michelle to confirm she can help with the GitHub demo so we can fill the schedule for the first 3 webinars this fall.

**Comment by Jegelewicz** [comment]
Let's take September since we don't have to plan from scratch unless Michelle wants to do Documentation then.

**Comment by ebraker** [comment]
we should put together a webinar abstract - do you think we should cover some of the metrics found throughout Arctos or just stick to the low quality dasboard and tools available for infilling data gaps?

**Comment by campmlc** [comment]
I like the idea of the dashboard showing some good metrics as well that we
can show to administrators and use for reports.

**Comment by dustymc** [comment]
Possibly-stoopid idea which everyone should feel completely comfortable ignoring: Take a quick detour into development/history-land. I'm not sure how, but I think it's important to emphasize that current Arctos reporting isn't what could be; there are ~∞ ways in which one could look at the data in Arctos (and beyond - eg, reports could easily pull from GenBank), and somewhat fewer ways to visualize the results of that.

Here's where I think we are now.

* various people asked for various statistics, mostly when Arctos was both smaller and simpler
* we did some stuff that more or less worked for that
* keeps happening, but there's no unity - these were built for, and often linked to, specific nodes/purposes
* dashboard idea comes along
* We now have a framework. It's easy to add arbitrary things to it. REALLY arbitrary if necessary - a report of Agents who've collected soricids in july and have a 7 in their phone number is completely possible and fairly easy. 
* Many of these queries are stupid-expensive (eg, sorting through 800 million taxon terms), so there's caching; the cost is paid for when the DB isn't busy, not while users are waiting for pages to load.
* The cache makes it cheap/easy to grab summary statistics, so we can sprinkle it around (eg, top of try something random).
* There's a simple UI "dashboard," but it was just the fastest/easiest way I could make the data accessible.
   * More tools might need funding, certainly needs discussion. 
    * I think there's some desire for a "brightly-colored boxes" UI
    * An API could support stats packages, external report services, etc.
    * Someone somewhere mentioned a subscription option (but see eg, https://github.com/ArctosDB/arctos/issues/1679 - do we as a community really want to make that easier to ignore? Maybe...)
    * etc. - not really many technical limitations here

We have carefully designed the datastore to readily support unanticipated queries, now we have a back-end tool that makes it easy to gather summary data in response to user's requests, and that in turn could be used to feed most anything.

**Comment by ebraker** [comment]
@Jegelewicz How about this for the abstract?:

Arctos, an online collaborative museum collection management solution, is capable of providing its users with several metrics. Collection statistics, reporting features, data quality feedback and discovery tools aid Arctos users in improving data and quantifying collections use and impact.

In this presentation, we will demonstrate some of the Arctos metrics and tools currently available as well as highlight the “Low Quality Data Dashboard.” Still in its infancy, this dashboard compiles data improvement opportunities for Arctos users, including automated suggestions to enhance data integrity and linkages. Many summary tools were initially developed by request in isolation from one another and placed in proximity to the data tables that they summarize. Ultimately, the Arctos community plans to bring these dispersed performance metrics together in a centralized dashboard to help Arctos collections better comprehend, visualize, and communicate their holdings and activities, both quantitatively and qualitatively. We invite suggestions and feedback for any metrics or enhancements users would like to see implemented to achieve these aims.

**Comment by Jegelewicz** [comment]
Given @dustymc comments, my only edit.

Arctos, an online collaborative museum collection management solution, is capable of providing its users with <strike>several</strike> **an infinite variety of** metrics. Collection statistics, reporting features, data quality feedback and discovery tools aid Arctos users in improving data and quantifying collections use and impact.

In this presentation, we will demonstrate some of the Arctos metrics and tools currently available as well as highlight the “Low Quality Data Dashboard.” Still in its infancy, this dashboard compiles data improvement opportunities for Arctos users, including automated suggestions to enhance data integrity and linkages. Many summary tools were initially developed by request in isolation from one another and placed in proximity to the data tables that they summarize. Ultimately, the Arctos community plans to bring these dispersed performance metrics together in a centralized dashboard to help Arctos collections better comprehend, visualize, and communicate their holdings and activities, both quantitatively and qualitatively. We invite suggestions and feedback for any metrics or enhancements users would like to see implemented to achieve these aims.

**Comment by ebraker** [comment]
@Jegelewicz Can we schedule a combo soundcheck/planning session soonish? I am free this Friday, and my schedule is fairly open next week. Let me know what works.

**Comment by Jegelewicz** [comment]
I have a thing all day Friday. Tuesday or Wednesday afternoon between 2 and 5?

**Comment by ebraker** [comment]
Sure - let's do Tuesday @ 2pm

**Comment by Jegelewicz** [comment]
Shall we meet in the Zoom Room or should we schedule to iDigBio room?

**Comment by Jegelewicz** [comment]
Also - should we just use our slide deck from SPNHC augmented with real-time Arctos examples?

**Comment by ebraker** [comment]
That's along the lines of what I was thinking...I'll reserve Adobe Connect room so we can sound check while chatting about content

**Comment by Jegelewicz** [comment]
You're the BEST!

**Comment by ebraker** [comment]
Teresa and I both noticed some timeout errors and slow-loading pages earlier today while trying to prep for webinar, specifically:
- 'see results as' specimen summary page
- 'see results as' graph
- review annotations page and unreviewed annotations link (from low-quality dashboard)

The 'see results as' pages timed out despite the same query working when run as a regular specimen search. Just checking to see if there was some sort of issue this morning or if we should avoid complex or large queries when live-demoing these tools. Mostly just putting it on your radar @dustymc
