### ISSUE TITLE
2017-11-14 Transactions and agents

### ISSUE THREAD

**Issue by ekrimmel** [ArctosDB/arctos-webinars#3]
**Scheduled** for Tuesday, November 14th at 3pm EST.

Michelle Koo slated to be one of the **presenters**.

iDigBio **calendar announcement** placehold [here](https://www.idigbio.org/content/arctos-webinar-series-episode-3).

**Comment by ekrimmel** [comment]
Edited topic to be "Transactions in Arctos (accessions, loans, permits, projects, and agents)"

@mkoo and @ccicero will present

**Comment by ekrimmel** [comment]
**Abstract** from Carla: 

Arctos is a community of museums that collaborate to manage and host their data online. Over 3 million records are publicly available at https://arctos.database.museum, a searchable biodiversity database for scientific research, resource management, and education. The Arctos database is used both for querying museum records (see webinars 1 and 2) and for managing information about the collections. 
This webinar will provide a short introduction to how transactions (accessions, loans, and permits) are managed in Arctos. Topics will include collection-level permissions and the basic tools for creating and updating different kinds of transactions, managing agents, and linking transactions to projects and media. 

**Presenter/s**:  Carla Cicero and Michelle Koo (Staff Curators, Museum of Vertebrate Zoology, University of California, Berkeley).

**Comment by ekrimmel** [comment]
Webinar and sound check scheduled on Adobe Connect

**Comment by mkoo** [comment]
All completed - on youtube and linked here: https://arctosdb.org/learn/webinars/
