### ISSUE TITLE
Intro to Teaching Collections in Arctos

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos-webinars#30]
CHAS?

**Comment by Jegelewicz** [comment]
@anna-chinn

**Comment by anna-chinn** [comment]
Sure! I could do a March or April slot.

**Comment by ebraker** [comment]
Wahoo, thanks! Let's plan on April 14.

**Comment by anna-chinn** [comment]
On the calendar!
I just browsed through other Arctos Teaching collections- Any interest in joining in, @mvzhuang or @srobson4?
I saw that UTEP is using projects to document specimen use in lab courses, which would be neat to talk about.

**Comment by anna-chinn** [comment]
I've been dumping my outline in this [Google Doc](https://docs.google.com/document/d/1fxn8H69Zvj2oDeER1c9JLuIRVOq7m-ifvOx2UjQKcCY/). Emily (or anyone else!), I would love feedback on the content, especially because my only concrete experiences dealing with a teaching collection has been here at CHAS. Thanks for any input!

**Comment by anna-chinn** [comment]
Proposed abstract:
While museum teaching collections are often maintained informally or as ad hoc resources, in Arctos, teaching collections use the same shared formal infrastructure more typical to scientific collection management. This webinar will highlight tools that integrate teaching and research collection management systems and that streamline day to day management activities, including loans, formalized taxonomy, and built-in label generation. The webinar will also cover resources that make objects and specimens more accessible to non-academic users, like museum educators, including search tools, images and media, and the Arctos projects module.
