### ISSUE TITLE
Intro to Botany Collections in Arctos

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos-webinars#32]

**Comment by Jegelewicz** [comment]
Maybe @mvzhuang ?

**Comment by ebraker** [comment]
Yes, and Steffi at UAM (soft commit for Fall 2021)

**Comment by Jegelewicz** [comment]
@ebraker I am DYING for you to publish the recording of this - it was soooo fantastic!!!

**Comment by ebraker** [comment]
@Jegelewicz it was available on our Youtube same day! Here you go: https://youtu.be/1zMgQYwWArI
