### ISSUE TITLE
Intro to non-insect Invertebrate Collections in Arctos

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos-webinars#33]
Teresa to ask Phyllis

**Comment by Jegelewicz** [comment]
@sharpphyl any chance you would be interested? I could ask the team here at NMMNH who are just starting to migrate inverts to help out....

**Comment by sharpphyl** [comment]
Tell me more.  Of course, I'm happy to help.

**Comment by ebraker** [comment]
@sharpphyl it would be a ~50 minute overview webinar of Arctos catered to Invert collections. We are creating a series of Intro webinars for different collection disciplines to draw in audiences from each type of collection. We already have a general overview [webinar](https://www.youtube.com/watch?v=78V3MG_tBc4&t=2171s), an [Intro to Cultural Collections ](https://www.youtube.com/watch?v=iVVq0HKbVNU&t=1s) webinar, and Dec 10th Derek will present an Intro to Entomology Collections, so you could model structure off of these webinars. Essentially this webinar would introduce Arctos and give basic overview of all of its features (e.g., searches, transactions, media, publications/projects, agents, taxonomy, linkages), but with your examples all emphasizing non-insect Inverts. You could also highlight WORMs and perhaps attributes or other Arctos features that are specifically tailored for managing invertebrate or lot-based collections. Does this sound doable?

**Comment by ebraker** [comment]
p.s. We have March 10, April 14, or May 12, 2020 slots available (all at 1pm MT).

**Comment by sharpphyl** [comment]
Sure, it's doable and I'll be happy to start the process with help from the other collections.  April or May are the best slots for me.

**Comment by ebraker** [comment]
Great! Let's plan on May 12, thanks!

**Comment by sharpphyl** [comment]
It's on my calendar.

**Comment by ebraker** [comment]
Awesome, thanks so much!

**Comment by ebraker** [comment]
@sharpphyl are you still ok to present a May 12 Intro webinar?

**Comment by sharpphyl** [comment]
Thanks for the reminder.  Yes, I think I can still do it since it's virtual anyway.  I'll look at the previous ones but may have some questions about content.  Could someone else with a non-insect invert collection share the stage and offer a different viewpoint and different activities that we may not use?

**Comment by sharpphyl** [comment]
For example, you mentioned "e.g., searches, transactions, media, publications/projects, agents, taxonomy, linkages" and I can speak to searches, image media, agents, and taxonomy, but I don't have linkages to speak of, no publications or projects, and the only transactions I deal with are accessions.   If another invert collection uses those features, it would be a more compete and helpful webinar, I think.   

There may be other topics I can include.  I'll start an outline.  I'm thinking data entry features and geolocation as especially helpful compared to other databases we've used.

**Comment by ebraker** [comment]
Excellent! I will reach out to a couple of folks to see if someone is willing to team up with you on this one. I think highlighting the features that make Arctos an especially frictionless system and set it apart are important to share in addition to a fly-through tour, so that will be great! In the meantime, if you could work on a draft webinar abstract, that would be good (examples [here](https://github.com/ArctosDB/arctos-webinars) - click on date links). I won't need it until ~27th so no rush.

**Comment by Jegelewicz** [comment]
@sharpphyl UTEP:Inv has some projects, loans and publications. I am REALLY overwhelmed right now and I just cannot take on another webinar at this time, but I'll try to put together some examples from that collection that you can use. @anna-chinn may also have some.

**Comment by anna-chinn** [comment]
This is an example for project linkages:
http://arctos.database.museum/project/10003138

It's a project that collates a series of freshwater snails that Frank Baker collected/traded and published in a reference book, but neglected to catalogue in our ledgers. CHAS originally digitized the specimens based on his hand written specimen labels and we've been slowly using the book to verify his illegible handwriting. The specimens show up associated with the project because they're all in a loan that's connected to the project.

Eventually, I'd like to add citations to all of the specimens that he explicitly references in the book and connect the project to the species that he described in the book (especially because, in large part, he did his own thing when it came to taxonomy).

**Comment by Jegelewicz** [comment]
> especially because, in large part, he did his own thing when it came to taxonomy

Oh, he definitely is not alone....

**Comment by ebraker** [comment]
> @sharpphyl UTEP:Inv has some projects, loans and publications. 

Maybe @mvzhuang may be able to help gather some examples?

**Comment by sharpphyl** [comment]
Thanks for all your input and comments.  Very helpful.  I'll be back in touch as I develop the outline.

**Comment by sharpphyl** [comment]
Anna, I looked at your project (http://arctos.database.museum/project/10003138) in test and I think it would be an excellent example for the webinar.  Would you be willing to join me to describe the project and how the Arctos format helps manage it?

**Comment by sharpphyl** [comment]
@ebraker  When will Aren's presentation _Introduction to Arctos for Mammal Collections_  be available on YouTube?  I'd like to see what he covered.  

Anna has agreed to share the stage with me and will present her Project  http://arctos.database.museum/project/10003138.  I'll have the outline to you shortly.

**Comment by ebraker** [comment]
Aren recorded half of his Arctos Mammal webinar, I imagine he will record the other half once Arctos is back up. There are other recorded Intro webinars you can reference: [Intro to Arctos](https://www.youtube.com/watch?v=78V3MG_tBc4&t=2176s), [Intro to Cultural Collections](https://www.youtube.com/watch?v=iVVq0HKbVNU), and [Intro to Ento Collections](https://www.youtube.com/watch?v=2nZS5zjiTp8&t=17s).

Good news that Anna will help out with Projects! She will record the Intro to Teaching Collections webinar as soon as Arctos is up, so there will be another Intro presentation for you to reference in the next week, but in the meantime you can check out her excellent [outline](https://docs.google.com/document/d/1fxn8H69Zvj2oDeER1c9JLuIRVOq7m-ifvOx2UjQKcCY/edit) as a guide. Hopefully Aren will finish up his recording available next week as well.

**Comment by sharpphyl** [comment]
Just to confirm, will the I"ntro to non-insect invertebrate Collections in Arctos" be done as a recorded webinar with attendees or just recorded and posted?

**Comment by ebraker** [comment]
Ideally it would be a live webinar with attendees so people can ask questions and be a bit more dynamic. However, it largely depends on your internet reliability now that presumably you'd be presenting from home. There's not a great way to test this, but if you haven't had issues with Zoom meetings freezing up, you are probably alright and we can do a sound check next week to see if all works well on your equipment. We could also try Zoom (either the Arctos room or I have a CU account) if that plays better with your computer vs. Adobe Connect. However, if it makes more sense for you to do a recording, that is OK given the unusual circumstances (@anna-chinn may want to weigh in since she was having a good deal of connectivity issues and will be highlighting Projects...).

**Comment by anna-chinn** [comment]
Our home internet was just upgraded yesterday, and the connection seems better today. Will definitely need to do another test, though (ideally long prior to the webinar). If I can make sure that all of the connection issues are ironed out, I'd be happy to show and tell the project. And who knows, maybe we'll be back in the office by mid-May!

**Comment by ebraker** [comment]
Wahoo on the upgraded internet! Yeah, maybe we can schedule a check-in early the week of April 27 so we can test connectivity and make a call on the webinar format before I send the calendar announcement off to iDigBio.

**Comment by sharpphyl** [comment]
So far I haven't had any Zoom freezing issues, but the internet from home is definitely slower with the entire neighborhood using it.  We'll test it and see if it works well. I understand the value of a live presentation, but also want it to go smoothly.  I think it's highly unlikely that I'll be back in the Museum by mid-May so let's assume I'll be using my home computer.

**Comment by ebraker** [comment]
@sharpphyl @anna-chinn  It looks like we can run a sound check in Adobe Connect most any time on 4/27 or 4/28. Is there a day or time that works better for either of you? I'm wide open.

**Comment by sharpphyl** [comment]
@anna-chinn  Do you use barcoding?  As I recall, you do, and that's why the consistency of higher classification is less critical to your collection.  We don't barcode, so taxonomy is critical to finding specimens in the collection.  I'm working up the abstract and just wanted to check with you.

**Comment by anna-chinn** [comment]
4/28 works better for me! I can do any time after 2PM Eastern (noon Mountain time).

@sharpphyl No we don't yet do any barcoding at CHAS, unfortunately. We just use part location attributes to track where everything is...

**Comment by dustymc** [comment]
>taxonomy is critical to finding specimens in the collection

What do you do when WoRMS splits a family or something? Drawing taxonomy from an auto-updated external source and confounding taxonomy with other stuff doesn't seem very compatible!

**Comment by Jegelewicz** [comment]
> What do you do when WoRMS splits a family or something?

Traditionally, you go move everything in your collection (there are still some people actually doing this!). Now, you just make some signage re-directs and hope the labels don't get too messy. Eventually everyone retires and no one knows where anything is for a while, then someone with spunk shows up and re-organizes it all according to "current" taxonomy. Repeat.

**Comment by sharpphyl** [comment]
@anna-chinn and @ebraker 
Here is a draft abstract for the webinar.  Please make any changes or additions you think would be helpful.  Emily, we need to double check that the links work as shifting into GitHub may have distorted some of them.

Date:  May 12, 2020
Time: 3 pm ET (???)
Presenters:  Phyllis Sharp - Zoology Departmental Associate, Denver Museum of Nature and Science, Marine Invertebrate Collection
Anna Chinn - Assistant Collections Manager, Chicago Academy of Sciences, Peggy Notebaert Nature Museum
Moderator:  Emily Braker (?)

Abstract: 
This webinar will highlight Arctos features that are most helpful to invertebrate collections.  Taxonomy is often a significant challenge for these collections.  Arctos has recently added the WoRMS (via Arctos) taxonomic source which links to all taxa in the World Register of Marine Species.  This externally-curated source has been used by the DMNS Marine Invertebrate Collection for several years with excellent results.  We will look at features of individual taxon records, how the WoRMS (via Arctos) taxonomic source feeds into specimen data, and how it supports accurate data entry at the single entry level and bulkloading.  

With an example from the Chicago Academy of Science, we will look at features of an invertebrate project and related publication.  If time allows, we will look how agents and media can be used to increase the value of specimen records.

Links to relevant pre-reading materials for best experience, including at least...

- Learn more about Arctos: https://arctosdb.org
- Recordings of past Arctos webinars: https://arctosdb.org/learn/webinars
- Arctos Data Portal: http://arctos.database.museum
- Arctos Handbook: http://handbook.arctosdb.org.  There are seven articles in the handbook about taxonomy.  This group are highly recommended.
            -  https://handbook.arctosdb.org/documentation/taxonomy.html
            -  https://handbook.arctosdb.org/how_to/How-to-Create-Taxa-in-Externally-Managed-Sources.html
         -  https://handbook.arctosdb.org/how_to/How-to-manage-taxonomic-classifications.html
         -  https://handbook.arctosdb.org/how_to/How_to_Edit_Taxa.html

How to get the most out of Adobe Connect: https://www.idigbio.org/wiki/index.php/Web_Conferencing 

World Register of Marine Species: http://www.marinespecies.org/
The Lymnaeidae of North and Middle America, Recent and Fossil: http://arctos.database.museum/project/10003138

**Comment by sharpphyl** [comment]
> taxonomy is critical to finding specimens in the collection

> What do you do when WoRMS splits a family or something? Drawing taxonomy from an auto-updated external source and confounding taxonomy with other stuff doesn't seem very compatible!

That is one of the issues I plan to address in the webinar.  Using WoRMS (via Arctos) has been a HUGE help for us, but it isn't perfect and it may not work for every collection.  It has helped us understand how an externally-curated source differs from a user-managed source.   It keeps the higher classification clean (assuming users don't introduce inconsistencies) but does not update or alert us to genus/species level changes.  There are ways to do this and I may need your help with some SQL.

Theresa's description of what you do to cope with changes in the higher classification is spot on.  We have a relatively small collection - about 45,000 lots.  Many of our lots are not yet labeled and we have plenty of room right now.  When there is a change (for example, _Charonia tritonis_ was moved from Ranellidae to Charoniidae (new family), we actually relabelled and moved everything into the correct place. I'm hoping that we'll have barcoding in a few years and then it won't matter what the label with the shell says as we'll always be able to find it anyway.  Anna uses part location attributes to record where the specimen is, so she's isn't as impacted by the higher classification changes.  

But Dusty's concern is valid.  Since our invertebrate collections use different classification sources, if those have different higher classifications (e.g. family), then searches may not return all the specimens in Arctos.  I'm going to try to address this a bit in the webinar (I have examples to show that), but it's probably still a committee topic.

**Comment by dustymc** [comment]
>still a committee topic

I can easily stuff whatever you're using for object tracking into part attribute "location." It's not an ideal solution (I don't think it's possible to overstate the importance of machine-readable labels) but it would immediately freeze your part location data and de-couple the confounded data; tomorrow's WoRMS update wouldn't mean you suddenly can't find your Someoldfamilyiidae.

**Comment by Jegelewicz** [comment]
Sigh - why can't we just get people to use barcodes? It costs as much as the new labels that need to be printed every time something is moved (you can print barcodes using MSWord onto regular old address labels for the purpose of labeling cabinets, shelves and boxes). Just barcoding cabinets and shelves would be enough IMO. You don't even need a scanner for this purpose if you also include human readable text on the printed barcodes and add appropriate labels to the barcodes in Arctos.

We are doing this at NMMNH and I hope we can write up something about how it works so that more people will be convinced.

**Comment by dustymc** [comment]
"Barcoding on a budget" would be a great webinar....

>don't even need a scanner

<img width="1040" alt="Screen Shot 2020-04-23 at 10 10 10 AM" src="https://user-images.githubusercontent.com/5720791/80128521-a628fe80-854a-11ea-9a1b-ff5b56c969d6.png">

But in general agreed, setting up the foundation for a true machine-readable-label-based system seems like time well spent and should be at least as functional as anything else, even if you can't do everything on the first pass.

**Comment by Jegelewicz** [comment]
I'm gonna get one of those and a holster....

**Comment by dustymc** [comment]
It's not very budget, but if you'd add one of [these](https://www.techradar.com/news/worlds-smallest-color-printer-can-print-on-anything-including-your-skin) to your belt....

I suppose we need to revisit our obviously short-sighted ideas about not being able to barcode actual parts!

**Comment by anna-chinn** [comment]
>  immediately freeze your part location data and de-couple the confounded data; tomorrow's WoRMS update wouldn't mean you suddenly can't find your Someoldfamilyiidae

I'm an advocate for this kind of combined approach! At the moment, _nothing_ is organized in our inverts collection, but (most) everything has a part location. Last summer, a couple of researchers visited to look at our freshwater mussels and said that the collection was completely unuseable in its current state of disorder. Knowing which cabinet/drawer specimens are in (using either barcodes or part locations) doesn't help if you're short on time and have to open all 30 cabinets to survey a single family, plus the drawers each contain a couple hundred vials... Some semblance of order is nice to expedite finding things, but I'm thankful every day that mollusks seem to stay where our part locations say they should be.

**Comment by sharpphyl** [comment]
I will say that unless someone has misread a label (which happens all too often) and put a specimen of  Colubrariidae in the Columbariidae, we are usually able to find specimens quickly with the family organization, but you have to allocate some time to moving specimens around.  Shells tend to be fairly durable and it gives us a chance to check on their condition, so it's ok for our invert collection.

**Comment by ebraker** [comment]
> Here is a draft abstract for the webinar. Please make any changes or additions you think would be helpful. 

Thanks @sharpphyl !

Here are some edits, take or leave 'em:

This webinar will provide an overview of Arctos while highlighting helpful features that support the management of non-insect invertebrate collections. Taxonomy often presents a significant challenge for invertebrate collections, and through a collaboration with the World Register of Marine Species, Arctos dynamically integrates WoRMS taxonomic source data to organize local name and classification structures. This externally-curated source has been used by the DMNS Marine Invertebrate Collection for several years with excellent results. We will look at features of individual taxon records, how the WoRMS (via Arctos) taxonomic source feeds into specimen data, and how it supports accurate data entry at the single entry level and through bulkloading. 

With an invertebrate example from the Chicago Academy of Science, we will demonstrate the Arctos Project and linked Publications features. If time allows, we will also review how Agents and Media can be used to increase the value of specimen records.

Also, I think we may want to leave the pre-reading links out of the announcement, but absolutely include them in the webinar. I don't know if you receive the NHCOLL emails, but if you subscribe to the plain text version, links are ridiculously long and visually cumbersome.

How about we meet 4/28 at 1pm MT (3pm ET @anna-chinn) ?

**Comment by ebraker** [comment]
> ust barcoding cabinets and shelves would be enough IMO. You don't even need a scanner for this purpose if you also include human readable text on the printed barcodes and add appropriate labels to the barcodes in Arctos.

> We are doing this at NMMNH and I hope we can write up something about how it works so that more people will be convinced.

We're doing a similar thing at UCM for tracking our wet specimens, I'll call it "barcode-adjacent." I think there's a good amount of push-back in the vertebrate community for barcoding legacy collections given the time-intensive and often monumental task of tag tying. However, smacking barcodes on jars/shelves/drawers is a great way to object track (and if you print labels, you can opportunistically add barcodes for new collections).

That said, I have also done a bunch of specimen moving to align collections with updated taxonomic standards, especially when the opportunity presents itself when we purchase new storage furniture and have to shuffle things anyway. Browsing collections through a primarily taxonomic filter (then geographic or temporal) is how the vast majority of collection users physically access biological collections (vs a temporal lens favored in paleo collections). At least one or two collections out there are experimenting with a totally non-systematic space-efficiency storage model completely reliant on object tracking - I can't fully wrap my mind around this for the same reasons Anna mentions.

Where moving collections to match current nomenclature/classifications is untenable, the good ol' "filed under" system seems to be what most institutions do (=update taxon name in DB and make a note that it's stored under an old name). Couple this analog-ish system with container locations, and you're good to go!

**Comment by dustymc** [comment]
> totally non-systematic space-efficiency storage model

The key to the container model is to make it work for you. If something has some sort of negative impact under some particular circumstances, then just don't do it - containers are whatever you say they are (plus parts), there are a LOT of recipes in that!

Even with no space constraints at all, my experience in barcoding a young collection of exclusively flat and square things curated by a very few meticulous people would still drive me to use barcodes for object tracking.

Barcodes are also useful for things other than permanent storage. Scanning a tray of butterflies into the lab, a sack of uncataloged rats into a prep freezer, parts into loans, updating identifications by scanning the barcodes of returning items, ..... - I suspect the collections that really use barcodes would still use them for those things even if they somehow didn't need to track storage location.

They're also pretty useful when something weird happens. 500 low-data lynx heads magically appear, barcode them and shove them in a corner somewhere, anyone can find them at any time even if there's been a complete turnover and all the stickynotes have fallen off. Someone sticks a shrew in with the mice, it could be gone for decades; someone scans a shrew in with the mice, anyone can find it. 

I really like machine-readable labels....

**Comment by sharpphyl** [comment]
@ebraker 

I'm fine with your edits and with leaving out the links to the various webpages.  You know best how to convey that information.  I have on my calendar the meeting at 1:00 on Monday the 24th.  I can do either a Zoom link or Adobe if you send the link.  Will we have time at this meeting to test our "screen share" or will we do that just before the presentation on May 12?

**Comment by ebraker** [comment]
Great. We'll meet Tuesday 4/28 @ 1pm MT since Tuesday is better for @anna-chinn - does that still work for you @sharpphyl ? We will check our sound and screen share capabilities. Here is the Adobe Connect link: https://idigbio.adobeconnect.com/room

**Comment by sharpphyl** [comment]
Sure, Tuesday the 28th works for me.

**Comment by anna-chinn** [comment]
4/28 @ 3PM Eastern works for me. See you both, then!

**Comment by sharpphyl** [comment]
@dustymc  I'm preparing for the Webinar next Tuesday and want to show how to see if a taxon name is valid in my particular source during single record data entry.  You stopped showing the taxon status in each Source, I think because it was too much data for Oracle/Arctos to handle.  I can show the same thing in the test field, but I want to be sure that's what it will look like in the final version so the Webinar doesn't become dated.

Here's what I get for Fargoa in the Scientific Name field under Identification currently in Arctos

![Screen Shot 2020-05-04 at 1 44 16 PM](https://user-images.githubusercontent.com/15368365/81006833-621ce000-8e0d-11ea-91c5-190b267503a6.png)

Here's what I get for Fargoa in the same field in test.Arctos.  

![Screen Shot 2020-05-04 at 1 44 01 PM](https://user-images.githubusercontent.com/15368365/81006882-78c33700-8e0d-11ea-9d00-261b7acc221f.png)


In both cases, I can choose to only show those names with a classification in my preferred source, but I want to show how it first pops up too.

**Comment by sharpphyl** [comment]
@anna-chinn 
Not sure you got my email suggesting a Zoom tomorrow to review our webinar for May 12th.  I can do it anytime that you're available but I suggested 1:00 Mountain time which, I think, is 2:00 your time.

**Comment by dustymc** [comment]
Yes I believe I was forced to pull that when it melted Oracle a few months back. The new infrastructure should handle that (and deeper views in general) and provide a realistic way to add the resources necessary if it won't.

**Comment by ebraker** [comment]
And @dustymc I'd like to confirm that we won't be migrating to PostGres on or before April 12 before I send out the webinar announcement to listservs (i.e. Production will be presumably up and functioning).

**Comment by dustymc** [comment]
That's a question for @ArctosDB/arctos-working-group-officers 

(I hope we will be in PG by then, but that can be scheduled and I don't think it'd be a problem to work around a webinar.)

**Comment by sharpphyl** [comment]
> And I'd like to confirm that we won't be migrating to PostGres on or before April 12

Just checking that you meant May 12th. 

If we might be switching over about that time, should we delay the webinar a week or so or go ahead?

**Comment by ebraker** [comment]
Sorry! Yes, I meant May 12... I think to be on the safe side we may want to delay rather than have any more scheduling hiccups. @sharpphyl @anna-chinn what do you think? May 19 or 26th? A different date?

**Comment by Jegelewicz** [comment]
As there is literally nobody but me testing ArctosPG right now as far as I can tell, the later, the better.

Dusty may have a different view if people are in test but not documenting it in GitHub.

**Comment by dustymc** [comment]
There are a few others plugging around in there. 

My view on the migration hasn't changed in a long time - the sooner the better.

**Comment by Jegelewicz** [comment]
I do not disagree, but we need to feel confident that we have tested. Right now, I don't feel that - maybe I am the only one who feels that way.

**Comment by ebraker** [comment]
I don't disagree on migrating sooner rather than later. I think scheduling the webinar farther out will allow users to poke around in untested corners of PG to largely ensure that we don't encounter them while broadcasting... (the alternative being that we present a webinar in Production next week, but this requires that the PG migration 2-day downtime does not overlap with the scheduled webinar)

**Comment by campmlc** [comment]
I'll be in test after this week. But we just sent out the clarification
email - perhaps others will join.

**Comment by dustymc** [comment]
Still not my call, but I don't think next week is likely, and I don't think scheduling around a webinar would be an issue.

**Comment by sharpphyl** [comment]
@ebraker , I'm find with delaying the webinar until either May 19th or 26 if it's ok with @anna-chinn.  What I'd rather not do is create a webinar that's partially in "test" and is out of date soon.  I'd rather have a week after Postgres to make all my links and know they'll be stable for a while.

**Comment by ccicero** [comment]
I suggest delaying as well. I don't recommend doing the webinar with the current prod version, it's super slower - at least for me!

**Comment by ebraker** [comment]
Ok, sounds like we should hold off. How about we tentatively set the webinar date to May 26th with  flexibility around delaying further if we haven't been in PG long enough to iron out the major kinks (~1 week min) @sharpphyl @anna-chinn

**Comment by sharpphyl** [comment]
It's on my calendar for May 26th.  Thanks.

**Comment by anna-chinn** [comment]
May 26th sounds good to me, too.

**Comment by sharpphyl** [comment]
I understand the transition to Postgres is more likely to be in early June rather than late May.  Since I'm having some issues creating some tutorials to augment the webinar, I'm wondering if we need to delay another few weeks until we're in Postgres and have had a few weeks to run through our presentation and know that everything is working as planned.

**Comment by ebraker** [comment]
@sharpphyl We had discussed doing it on May 26 in the AWG meeting yesterday. That way the webinar would be in Production vs PG. It sounds like we will set a PG migration date (after May 26), so that would push the webinar likely into mid-June. Up to you and @anna-chinn but sooner might be better? Also, THANK YOU for making tutorials! :)

**Comment by sharpphyl** [comment]
Let's see what Anna thinks, but I just tried to update metadata on a taxon name and it literally took over 3 minutes before it was done churning.  That would not work well on a live webinar and I hate to limit ourselves to just the simplest screens for fear that we'll time out.  If it totally messes up your schedule, then we can give it a try.  

And the first tutorial I started to do involved the "invalid" taxon name issue, so I haven't made much progress yet but I'll keep trying.

**Comment by anna-chinn** [comment]
May 26 still works for me, but I could hold off until post-PG if need be. That said, too much later than mid-June/July and I will likely have much less consistent availability. 

Phyllis, I've also been experiencing bad lag on taxon name/classification updates and I can definitely understand your hesitation. While being unable to save updates in real time isn't ideal, we can still show off the different kinds of taxon name and classification metadata that can be added and how the metadata impact how records appear in searches and how they relate specimens to one another.

To me, the webinar audience and the tutorial audience are different (live webinars more for prospective collections, tutorials for current Arctos users). If the sticking point is creating the complementary tutorials, I think that having them available as eventual resources is good enough, especially if the lag time is only a month or so.

**Comment by sharpphyl** [comment]
Let's see how our practice run-through goes on Thursday.  I think we can make it work and stick with the May 26th date.  I may have to use the "test" site but I'm doing that on some tutorials as well.  There will always be a "life" to these videos and sometimes we'll have to update or redo them.

**Comment by ebraker** [comment]
Sounds good. Let me know your final call ASAP after your practice goes on Thursday so I can send out a list serv announcement.

**Comment by sharpphyl** [comment]
@dustymc 

Media doesn't seem to be working. 

![Screen Shot 2020-05-25 at 10 00 49 AM](https://user-images.githubusercontent.com/15368365/82828683-dd9f0980-9e6e-11ea-95fd-8495033dd86b.png)

![Screen Shot 2020-05-25 at 10 00 58 AM](https://user-images.githubusercontent.com/15368365/82828672-d841bf00-9e6e-11ea-85fb-b3884099643e.png)

I'm in Firefox because Chrome still is showing that we don't have a certificate.  We have a Webinar tomorrow and would like to show media.  Can go without it but need to know what to do.

**Comment by sharpphyl** [comment]
It's fixed.  Thanks.

**Comment by ebraker** [comment]
Well done!

**Comment by Jegelewicz** [comment]
This was an awesome webinar!!!! Thanks @sharpphyl and @anna-chinn!!!!

**Comment by sharpphyl** [comment]
Whew!  Glad it was helpful.
