### ISSUE TITLE
Intro to Mammal Collections in Arctos

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos-webinars#34]
Link? Aren?

**Comment by amgunderson** [comment]
Yeah I can do this. Do I get a choice of dates?

**Comment by ebraker** [comment]
Absolutely! I had written you down more as a note to myself to formally ask you a couple of weeks down the road, so yay, thanks for being proactively willing to present! You would have your choice of March, April or May 2020

**Comment by ebraker** [comment]
Actually, @amgunderson are you able to do March 10? We've got folks signing up for other time slots.

**Comment by amgunderson** [comment]
Sure March 10 is good.

**Comment by ebraker** [comment]
Excellent, thanks so much Aren!
