### ISSUE TITLE
Arctos Office Open Hours III

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos-webinars#37]
Any volunteers to help field questions for the 3rd edition of Office Hours? It will take place on January 14th @ 1pm MT. I'm thinking that if we have time at the end we can mention/demonstrate some of the recent code table changes in Arctos, e.g. Catalog Record and Nature of ID terms (and whatever else we'd like to include).

I've started a [google doc](https://docs.google.com/document/d/1hTzfSQdnodprNzFr5fpbfHNMtuetjOpA2ERHLLp20BQ/edit?usp=sharing) for questions and will share it at the Dec 10th webinar.

**Comment by campmlc** [comment]
I can help.
Mariel

**Comment by ebraker** [comment]
thanks @campmlc !

**Comment by Jegelewicz** [comment]
Me for sure!

**Comment by ebraker** [comment]
Wahoo! Thanks @Jegelewicz

**Comment by AJLinn** [comment]
I should be able to be online in case cultural collection questions arise.

**Comment by ebraker** [comment]
Awesome, thanks @AJLinn !
