### ISSUE TITLE
New Collections Onboarding

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos-webinars#39]
tentative October 13, 2020 - presenters needed!

**Comment by Jegelewicz** [comment]
That's me....

**Comment by ebraker** [comment]
Fantastic! Thank you!

**Comment by Jegelewicz** [comment]
**Abstract draft**

Joining the Arctos Community means meeting new collaborators, learning new skills, and a lot of data clean-up. Whether you joined five years ago, last week, plan to join soon, or want to help mentor new members, this webinar will help explain the process we have set up to help new members of the Arctos Community get their collections up and running. Learn why we use GitHub, how to best get help, who has the answers and where to find documentation. Onboarding never really ends, even our most senior community members are adding new types of collections data. The process that we use for onboarding extends into daily Arctos Community life, so the practices that you pick up during onboarding can serve you well into the future. Hope to see everyone at this webinar!

**Comment by Jegelewicz** [comment]
@ebraker abstract above. @mkoo @campmlc @ccicero @acdoll please edit if it needs it!

**Comment by campmlc** [comment]
Looks great! Let me know what I can do to help.

**Comment by ebraker** [comment]
Love it, thanks @Jegelewicz !
