### ISSUE TITLE
2018-02-13 Data cleaning tools for use prior to migrating into Arctos

### ISSUE THREAD

**Issue by ekrimmel** [ArctosDB/arctos-webinars#4]
Want a webinar to address tools such as Arctos pre-bulkloaders, Kurator, OpenRefine, etc.

@ekrimmel potentially to present.

Tentatively scheduled for December 2017.

**Comment by ekrimmel** [comment]
**Abstract:** Arctos is both a community and a collection management information system. It provides fundamental research infrastructure for biodiversity data, and is intended for curators, collection managers, investigators, educators, and anyone interested in natural and cultural history. Over 3 million records are publicly available from 20+ collaborating institutions.

This webinar will cover several available tools you can use to review and clean collections data in preparation for migrating into Arctos. In addition to the tools embedded within Arctos to validate agent names, taxonomy, and higher geography, we will include an overview of the program OpenRefine. We will also discuss basic tips for cleaning data, and touch on additional services such as KuratorWeb.

**Comment by ekrimmel** [comment]
need to fix date! February 12 is a Monday, should be the second Tuesday, i.e. Feb 13th.

**Comment by ebraker** [comment]
@ekrimmel Do you want me to email Molly Phillips to get the date changed on the iDigBio calendar?

**Comment by ekrimmel** [comment]
Date fixed. Andrew Doll added as co-presenter.

**Comment by mkoo** [comment]
Posted on arctosdb.org and youtube
