### ISSUE TITLE
Bionomia and Arctos

### ISSUE THREAD

**Issue by ebraker** [ArctosDB/arctos-webinars#49]
David to present on 4/12/2022

**Comment by campmlc** [comment]
More info?

**Comment by ebraker** [comment]
David Shorthouse will present a webinar with an overview of Bionomia and how Arctos data are ingested. I'm sure he will cover the ways ORCIDs and wikidata plug in and the metrics and tools available to assign attribution, showcase collectors etc. This is a great resource for agent names and an external counterpoint to agent activity.

**Comment by campmlc** [comment]
Great! and will there be info on the link closer to the time?

**Comment by ebraker** [comment]
Yup! I'll post his abstract and Zoom link in early April.
