### ISSUE TITLE
2018-01-09 Data Entry and Bulkloading

### ISSUE THREAD

**Issue by ekrimmel** [ArctosDB/arctos-webinars#5]
Want a webinar to cover how to get new data into Arctos, namely via direct data entry vs. the bulkloader.

@ebraker volunteered to present.

Tentatively scheduled for January 2018.

**Comment by ekrimmel** [comment]
**Potential abstract:** Arctos is both a community and a collection management information system. It provides fundamental research infrastructure for biodiversity data, and is intended for curators, collection managers, investigators, educators, and anyone interested in natural and cultural history. Over 3 million records are publicly available from 20+ collaborating institutions.

This webinar will cover the two primary methods for getting data into Arctos: data entry and bulkloading. While data entry provides a simple interface to enter data for specimens individually, bulkloading allows the user to upload a .csv file of multiple records. Both methods incorporate tools for data standardization and basic cleaning prior.

**Comment by ekrimmel** [comment]
@ebraker does the potential abstract (above) for your January webinar look alright? Make any edits you'd like, and I'll send it along to iDigBio to update the [calendar event](https://www.idigbio.org/content/arctos-webinar-series-data-entry-and-bulkloading). I know it's more than 2 months off still, but these webinars get linked on the iDigBio newsletter early and it's best for people not to open a link to a page with no info.... thanks!

**Comment by ebraker** [comment]
@ekrimmel The summary looks great! Thank you for preparing it and apologies I missed this thread.

**Comment by Jegelewicz** [comment]
@ebraker if you want someone to ride along with you for this one, I would be happy to help out.

**Comment by ekrimmel** [comment]
We've found that two webinar presenters works really nicely, as one can field questions in the chat while the other is sharing their screen, so I think this is a great offer. Could be easy for @ebraker to do the primary presenting but have @Jegelewicz on hand for that extra chat and Q&A support, or have the two of you break up presenting between bulkloader vs. data entry, or anything in between...

**Comment by ebraker** [comment]
@Jegelewicz That would be great, thanks for offering. I'd be happy for some assist with fielding chat and general questions and any tips you have up your sleeve.

**Comment by Jegelewicz** [comment]
@ebraker Great! Do you already have a presentation set up or a script? If so, pass it along so I can get prepared! If you want help developing one, I can do that too. I'll be happy to manage the chat and share anything that seems useful as questions and comments arise.

**Comment by ebraker** [comment]
@Jegelewicz No presentation set up yet. We are moving our entire Herp collection in preparation for new static shelving and compactors (phase I is in December - which is nearly upon us) so I am knee-deep in jar-hauling and taxonomic updating. I will pass on what I have once I have it, likely late December.

**Comment by ekrimmel** [comment]
survey link from Shari: https://tinyurl.com/iDigBioArctosWebinar5

**Comment by ekrimmel** [comment]
recording made: https://www.youtube.com/watch?v=fUE5deS_hLo&list=PLA1YSv1rn8XcR6Pe0qyNuM8h07GB87bMh&index=6

**Comment by mkoo** [comment]
Posted on arctosdb.org and youtube
