### ISSUE TITLE
Understanding Localities and Geospatial Tools

### ISSUE THREAD

**Issue by ekrimmel** [ArctosDB/arctos-webinars#6]
Want a webinar to cover how Arctos models spatial data and what tools it has to handle spatial data needs.

@mkoo volunteered to present.

Tentatively scheduled for February 2018.

**Comment by ekrimmel** [comment]
**Potential abstract:** Arctos is both a community and a collection management information system. It provides fundamental research infrastructure for biodiversity data, and is intended for curators, collection managers, investigators, educators, and anyone interested in natural and cultural history. Over 3 million records are publicly available from 20+ collaborating institutions.

This webinar will introduce the model Arctos uses for locality information, then describe geospatial tools available for georeferencing, searching, visualizing, etc.

**Comment by ekrimmel** [comment]
Scheduled with iDigBio but probably need to reschedule as Michelle may be out of town

**Comment by ekrimmel** [comment]
Postponed until geography is less of a moving target.

**Comment by Jegelewicz** [comment]
Split into issue #20  and #21
