### ISSUE TITLE
2018-12 Taxonomy

### ISSUE THREAD

**Issue by ekrimmel** [ArctosDB/arctos-webinars#7]
Want a webinar to cover how Arctos handles taxonomic data.

Andy Doll volunteered to present along with, perhaps, Derek Sikes.

Tentatively scheduled for March 2018.

**Comment by Jegelewicz** [comment]
From 2018-07-12 AEG notes:

> December: Taxonomy (Teresa to help; Mariel to help; Carol?)

**Comment by campmlc** [comment]
@DerekSikes ?

**Comment by DerekSikes** [comment]
I could help with this but I only know the basics. I haven't played with the new classification tool.

**Comment by Jegelewicz** [comment]
@ArctosDB/taxonomy to prepare for this webinar on Date: Tuesday, December 11, 2018 at Time: 12 PDT/ 3pm EDT

Read documentation and take notes on ambiguities:
https://arctosdb.org/about/details/taxonomy/
http://handbook.arctosdb.org/documentation/taxonomy.html
http://handbook.arctosdb.org/how_to/How-to-manage-taxonomic-classifications.html
http://handbook.arctosdb.org/how_to/How-to-Manage-Taxonomy-Hierarchically.html

http://handbook.arctosdb.org/documentation/identification.html

**Comment by Jegelewicz** [comment]
We would like to schedule a sound check/ run through on Wednesday, December 5th at 11am. @ebraker @KyndallH

**Comment by ebraker** [comment]
Soundcheck reserved for Weds, December 5th at 11:15 am MT here: https://idigbio.adobeconnect.com/room
