### ISSUE TITLE
2018-04-10 Object Tracking with Containers

### ISSUE THREAD

**Issue by ekrimmel** [ArctosDB/arctos-webinars#9]
Want a webinar covering object tracking with containers, using tissues as an example.

@campmlc and @KyndallH volunteered to present.

Tentatively scheduled for May 2018.

**Comment by campmlc** [comment]
Ok

On Oct 3, 2017 9:22 AM, "Erica Krimmel" <notifications@github.com> wrote:

Want a webinar covering object tracking with containers, using tissues as
an example.

@campmlc <https://github.com/campmlc> and @KyndallH
<https://github.com/kyndallh> volunteered to present.

Tentatively scheduled for May 2018.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ChicagoAcademyofSciences/arctos-webinars/issues/9>, or mute
the thread

**Comment by ekrimmel** [comment]
Another vote for this topic...

> Name: Shannen Robson 
Email: robson@nhmu.utah.edu 
Message: Not a new topic for webinar, but a second for 'tissues, containers, and object tracking'. A 2018 project for UMNH is to barcode and track our tissue library. Would love a webinar on this before we start.

**Comment by dustymc** [comment]
Suggestion: Include a brief overview of things other than object tracking which barcodes can make (much!) easier.

* adding items to loans
* tracking loaned material
* LIMS-type data (what happens between a loan and a publication)
* tracking lot history
* semi-automated imaging
* finding specimens (e.g., as a proxy to catalog number)
* bulkloading part attributes (and anything else which involves identifying specific parts)
* recording "container environment" such as ethanol concentration, freezer failures, etc. (maybe that's object tracking)

Or maybe that's another webinar??

**Comment by campmlc** [comment]
This might be worth a long entry in the handbook as well.

**Comment by ekrimmel** [comment]
True, in fact it might be a good idea to have presenters for any webinars review and add to any relevant Handbook pages when they are preparing their webinars. The outlines presenters have been making are really detailed and in some cases have good info that I don't think is already well-documented. Don't want to scare people off from presenting, but if you're already thinking about how to explain something...........

**Comment by campmlc** [comment]
AWG meeting suggestions: 

6 - super (RNA quality)
5 - excellent (genomic quality)
4-  very good (genomic quality)
3 - good (DNA quality)
2 - fair (possibly DNA quality)
1 - poor (unknown quality)

**Comment by ebraker** [comment]
Abstract (from Mariel and Kyndall): Arctos manages over 2 million physical objects using a sophisticated object tracking system. Both barcoded and non-barcoded objects are trackable through use of labels. Labels can be attached to any object or container as a means of linking the container environment to the specimen record.  Arctos creates a hierarchical map of an object’s physical location from the building down to the position in a tray, shelf, or freezer box, to the actual collection object or specimen part, making it easy to pinpoint the exact location. To prevent duplicates, the object tracking feature can accept 1D or 2D barcodes or any string of unique characters that are machine readable. Each barcoded or labeled part is linked to and trackable from the specimen record in the museum collections database. When a part is moved and scanned into a new location, the specimen record is automatically updated. Arctos object tracking also provides logging of container history and environment. Barcodes can be assigned in the field and applied to data sheets to track samples from the point of collection through accession, curation, and loans. This webinar will provide information how to use and get the most out of the object tracking system in Arctos.
